[package]
name = "rust-rain"
version = "0.1.0"
authors = ["Mike Stipicevic <stipredirect@gmail.com>"]
edition = "2018"

[[bin]]
name = "rain"
path = "src/main.rs"

[dependencies]
structopt = "0.2.15"
rand = "0.6.0"
termion = "1.5.0"
