[package]
name = "rust-rain"
version = "0.2.0"
authors = ["Mike Stipicevic <stipredirect@gmail.com>"]
edition = "2018"

[[bin]]
name = "rain"
path = "src/main.rs"

[dependencies]
ctrlc = "3.1.4"
fps_clock = "2.0.0"
rand = "0.7.3"
rand_distr = "0.2.2"
structopt = "0.3.7"
termion = "1.5.5"
