[package]
name = "rust-rain"
version = "0.2.0"
authors = ["Mike Stipicevic <stipredirect@gmail.com>"]
edition = "2018"

[[bin]]
name = "rain"
path = "src/main.rs"

[dependencies]
ctrlc = "3.1.3"
fps_clock = "2.0.0"
rand = "0.7.0"
rand_distr = "0.2.1"
structopt = "0.3.0"
termion = "1.5.3"
